### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by byte-is-null** [byte-is-null/contact-info#2]
big b- buugs in "hello_world.py" AAAAAAAAAAAAAA can anyone help debugg and try run pleeasee??? thanksss guys && lovee yall

**Comment by Kourva** [comment]
Hi @byte-is-null , i did not understand well, but do you want something like this?
and also what is `x` variable ?

```python
import itertools, time

for a, b, c in itertools.product(range(20), range(10), range(10)):
    print(a, b, c)
    time.sleep(0.02)  # 20ms delay between each character

# i put range(20) in first argument of itertools.product, so we don't need to use break
```
output:
```
001
002
003
004

...

19 9 9
```
good luck

###### Edited:
I found that problem was itertools.count(0)
also above solution is written in python3, not python2:

**Comment by byte-is-null** [comment]
omgg thanks for helping @Kourva !! 

just wanted it to print "hello world" with 20ms delayyyy in python (sounds kinda cool) 😭 😭 😭 , crashed when used that code copyed from internet. created new branch called `possible-solutions` , could anyone with working solution submit pull request [there](https://github.com/byte-is-null/contact-info/tree/possible-solutions)? 

format: \<github username\>.py 

all working solutions will be reviewed and merged, tysm guys! yall are the beest

**Comment by Kourva** [comment]
> omgg thanks for helping @Kourva !!
> 
> just wanted it to print "hello world" with 20ms delayyyy in python (sounds kinda cool) sob sob sob , crashed when used that code copyed from internet. created new branch called `possible-solutions` , could anyone with working solution submit pull request [there](https://github.com/byte-is-null/contact-info/tree/possible-solutions)?
> 
> format: <github username>.py
> 
> all working solutions will be reviewed and merged, tysm guys! yall are the beest

So , it's too easy
```python
import time
for i in range(10):        # how many time you want to print 'hwllo world!'
    print("hello world!")  # print 'hello world!'
    time.sleep(0.02)       # sleep 20ms
```
This will print 'hello world!' 10 times.

**Comment by byte-is-null** [comment]
woww that worksss 😱 , i would like each character to be printed seperately 20ms apart tho, is that possible?? thankss a lot, do submit pull request once you are done too 🙏

**Comment by Kourva** [comment]
> 



> woww that worksss scream , i would like each character to be printed seperately 20ms apart tho, is that possible?? thankss a lot, do submit pull request once you are done too pray

Yes you can.
+ first way is using `sys` built-in module
+ Second way is just print each character normally without using new line
```python
import time, sys

text = "Hello world!"

# First way
for character in text:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(0.02)

# Second way
for character in text:
    print(character, end="", flush=True)
    time.sleep(0.02)
```

**Comment by byte-is-null** [comment]
yayy it workss!!! 😃 thaank you veery much for this solution! other solutions are welcomed too

**Comment by Kourva** [comment]
> yayy it workss!!! smiley thaank you veery much for this solution! other solutions are welcomed too

You're welcome.

**Comment by byte-is-null** [comment]
fixed
